name: "Position Collect Android"

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
      - main

# on: push    # Default will running for every branch.

jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      # Setup Java environment in order to build the Android app.
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter --version
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - run: flutter pub get
      - run: flutter format .
      - run: flutter build apk
      - run: flutter build appbundle
